version: '3.8'

services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: coursesphere_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: coursesphere
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Backend FastAPI
  backend:
    build: ./backend
    container_name: coursesphere_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  # Frontend React
  frontend:
    build: ./frontend
    container_name: coursesphere_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
  # Testes para Backend
  backend_test:
    build: ./backend
    container_name: coursesphere_backend_test
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    command: pytest -v
    profiles:
      - test
  
  # Testes para Frontend
  frontend_test:
    build: ./frontend
    container_name: coursesphere_frontend_test
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run test:run
    profiles:
      - test
volumes:
  pgdata: